name: CI

on:
  push:
    branches:
    - master
    - next
  pull_request:
    branches:
    - master
    - next

env:
    CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run rustfmt
      run: cargo fmt -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run clippy
      continue-on-error: true
      run: cargo clippy -- -D warnings

  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --manifest-path=eye/Cargo.toml

  check:
    name: check
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check
      run: cargo check
    - name: Check examples
      run: cargo check --manifest-path=eye/Cargo.toml --examples

  check-hals:
    name: check-hals
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - build: v4l2-ubuntu
          os: ubuntu-18.04
          rust: stable
          features: ""
        - build: openpnp-macos
          os: macos-10.15
          rust: stable
          features: ""
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check
      run: cargo check --manifest-path=eye/Cargo.toml ${{ matrix.features }}
